### ISSUE TITLE
А вот еще один интересный вопрос.

### ISSUE THREAD

**Issue by Razzwan** [MrZaYaC/ng2-webstorm-snippets#2]
Привет. Не знаю, как связаться с тобой другим способом, но вижу, что ты кое-как разбираешься в современных технологиях. Пиши мне в gitter-e или скайпе: pavel_belick - возможно будем друг другу полезны ;)

**Comment by MrZaYaC** [comment]
"кое-как" ? ну спасибо за комплимент )

**Comment by Razzwan** [comment]
У меня недостаточно компетенции, чтоб по достоинству оценить. Не хотел обидеть )
